name: Increment Version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  increment-version:
    runs-on: ubuntu-latest

    # Evita loop cuando el commit lo hace github-actions
    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Detect version type
        id: version_type
        run: |
          MESSAGE=$(git log -1 --pretty=%B)

          if [[ "$MESSAGE" == *"#major"* ]]; then
            echo "TYPE=major" >> $GITHUB_ENV
          elif [[ "$MESSAGE" == *"#minor"* ]]; then
            echo "TYPE=minor" >> $GITHUB_ENV
          else
            echo "TYPE=patch" >> $GITHUB_ENV
          fi

      - name: Increment version
        run: |
          NEW_VERSION=$(npm version $TYPE -m "Incrementando Version a %s")
          echo "New version: $NEW_VERSION"

      - name: Push changes
        run: |
          git push
          git push --tags