
name: Increment Version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Check working directory status
        run: |
          if ! git diff-index --quiet HEAD --; then
            git stash
          fi
      - name: Increment version
        id: increment_version
        run: |
          NEW_VERSION=$(npm version patch -m "Incrementando Version a %s")
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "name=$NEW_VERSION" >> $GITHUB_OUTPUT
      - name: Push changes
        run: |
          git push